name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Named step
        run: echo "Step"
      - run: date
      - run: ls -l