name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'Hello, world!'
      - run: echo 'Hello, world!'
      - run: echo 'Hello, world!'
      - run: echo 'Hello, world!'
      - run: echo 'Hello, world!'
      - run: echo 'Hello, world!'
      - run: echo 'Hello, world!'
      - run: echo 'Hello, world!'